-- MySQL Script generated by MySQL Workbench
-- mar. 01 sept. 2015 15:45:25 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ogs_stats
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ogs_stats
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ogs_stats` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `ogs_stats` ;

-- -----------------------------------------------------
-- Table `ogs_stats`.`modules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ogs_stats`.`modules` (
  `id` INT(11) NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `version` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ogs_stats`.`ogspy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ogs_stats`.`ogspy` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `ogspy_index` VARCHAR(20) NOT NULL COMMENT '',
  `version` VARCHAR(10) NOT NULL COMMENT '',
  `last_seen` DATE NOT NULL COMMENT '',
  `users` INT(11) NOT NULL COMMENT '',
  `db_size` INT(11) NOT NULL COMMENT '',
  `xtense_Firefox` INT(11) NOT NULL COMMENT '',
  `xtense_Chrome` INT(11) NOT NULL COMMENT '',
  `xtense_GM` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ogs_stats`.`ogspy_has_modules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ogs_stats`.`ogspy_has_modules` (
  `ogspy_id` INT(11) NOT NULL COMMENT '',
  `modules_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`ogspy_id`, `modules_id`)  COMMENT '',
  INDEX `fk_ogspy_has_modules_modules1_idx` (`modules_id` ASC)  COMMENT '',
  INDEX `fk_ogspy_has_modules_ogspy_idx` (`ogspy_id` ASC)  COMMENT '',
  CONSTRAINT `fk_ogspy_has_modules_ogspy`
    FOREIGN KEY (`ogspy_id`)
    REFERENCES `ogs_stats`.`ogspy` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ogspy_has_modules_modules1`
    FOREIGN KEY (`modules_id`)
    REFERENCES `ogs_stats`.`modules` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
